### ISSUE TITLE
Compile error at "python build_extend_utils_cffi.py"

### ISSUE THREAD

**Issue by QiangZiBro** [zju3dv/pvnet#117]
Dear author, I tried to compile in 3rd step, and below is error message. My gcc version is 5.4.0 and I have modified `cuda_include` to `...cuda-10...` in my environment.
```
/usr/local/cuda-10.0/include/crt/sm_70_rt.h(106): warning: missing return statement at end of non-void function "__match_all_sync(unsigned int, unsigned long long, int *)"

/usr/local/cuda-10.0/include/crt/sm_70_rt.h(107): warning: missing return statement at end of non-void function "__match_all_sync(unsigned int, long long, int *)"

/usr/local/cuda-10.0/include/crt/sm_70_rt.h(108): warning: missing return statement at end of non-void function "__match_all_sync(unsigned int, float, int *)"

/usr/local/cuda-10.0/include/crt/sm_70_rt.h(109): warning: missing return statement at end of non-void function "__match_all_sync(unsigned int, double, int *)"

In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h:217:0:
/usr/local/cuda-10.0/include/crt/host_runtime.h:19:2: warning: #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_ap
  ^
In file included from /tmp/tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:5:0,
                 from tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:
/usr/local/cuda-10.0/include/crt/host_runtime.h:19:2: warning: #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "crt/device_functions.h is an internal header file and must not be used directly.  Please use cuda_runtime_ap
  ^
In file included from tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:0:
/tmp/tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c: In function ‘void __device_stub__Z27findNearestPoint3DIdxKernelPfS_Piiiii(float*, float*, int*, int, int, int, int)’:
/tmp/tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:11:153: error: ‘__args_arr’ was not declared in this scope
 ernelPfS_Piiiii(float *__par0, float *__par1, int *__par2, int __par3, int __par4, int __par5, int __par6){__cudaSetup
                                                                                                            ^
/tmp/tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:11:164: error: ‘__args_idx’ was not declared in this scope
 iiii(float *__par0, float *__par1, int *__par2, int __par3, int __par4, int __par5, int __par6){__cudaSetupArgSimple(_
                                                                                                            ^
In file included from tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:0:
/tmp/tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c: In function ‘void __device_stub__Z27findNearestPoint2DIdxKernelPfS_Piiiii(float*, float*, int*, int, int, int, int)’:
/tmp/tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:162: error: ‘__args_arr’ was not declared in this scope
/tmp/tmpxft_00005c4d_00000000-4_nearest_neighborhood.cudafe1.stub.c:1:173: error: ‘__args_idx’ was not declared in this scope
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/home/qiangzibro/docker/pvnet/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
gcc -pthread -B /home/qiangzibro/anaconda3/envs/pvnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/qiangzibro/anaconda3/envs/pvnet/include/python3.6m -c _extend_utils.c -o ./_extend_utils.o
gcc -pthread -shared -B /home/qiangzibro/anaconda3/envs/pvnet/compiler_compat -L/home/qiangzibro/anaconda3/envs/pvnet/lib -Wl,-rpath=/home/qiangzibro/anaconda3/envs/pvnet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-10.0/lib64/libcudart.so -lstdc++ -o ./_extend_utils.cpython-36m-x86_64-linux-gnu.so
gcc: error: src/uncertainty_pnp.cpp.o: 没有那个文件或目录
gcc: error: ./lib/libceres.so: 没有那个文件或目录
gcc: error: ./lib/libglog.so: 没有那个文件或目录
Traceback (most recent call last):
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 39, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/qiangzibro/anaconda3/envs/pvnet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

```

**Comment by pengsida** [comment]
What directory did you perform this command at?
![image](https://user-images.githubusercontent.com/11582122/72152791-ff7b8080-33e6-11ea-8e5d-2a8ab19c360c.png)

**Comment by QiangZiBro** [comment]
> What directory did you perform this command at?
> ![image](https://user-images.githubusercontent.com/11582122/72152791-ff7b8080-33e6-11ea-8e5d-2a8ab19c360c.png)

I reopen an issue,  all environment config consists in docker file, you can see step 2 and 3
