### ISSUE TITLE
Error building build_extend_utils_cffi.py

### ISSUE THREAD

**Issue by Hao-HUST** [zju3dv/pvnet#14]
Hi, 

Thanks for sharing your great work. 

When I run the python script  build_extend_utils_cffi.py, the error is : 

python build_extend_utils_cffi.py
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/root/Project/Image-based_Cabinet_Modeling/pvnet/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
gcc -pthread -B /root/anaconda2/envs/image_cabinet/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda2/envs/image_cabinet/include/python2.7 -c _extend_utils.c -o ./_extend_utils.o
gcc -pthread -shared -B /root/anaconda2/envs/image_cabinet/compiler_compat -L/root/anaconda2/envs/image_cabinet/lib -Wl,-rpath=/root/anaconda2/envs/image_cabinet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-9.0/lib64/libcudart.so -L/root/anaconda2/envs/image_cabinet/lib -lstdc++ -lpython2.7 -o ./_extend_utils.so
/root/anaconda2/envs/image_cabinet/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script
/root/anaconda2/envs/image_cabinet/compiler_compat/ld:./lib/libceres.so:0: syntax error
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 41, in <module>
    ffibuilder.compile(verbose=True)
  File "/root/anaconda2/envs/image_cabinet/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/root/anaconda2/envs/image_cabinet/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/root/anaconda2/envs/image_cabinet/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/root/anaconda2/envs/image_cabinet/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

Are there any suggestions about that? My environment is Ubuntu 16.04+gcc 5.4.0+cuda 9.0. 

Thanks again.

**Comment by pengsida** [comment]
Use python3 and ensure the OS is 64 bit.

**Comment by Hao-HUST** [comment]
Hi, as you suggested, I use the python 3.6 and compile the script again, but it still failed:

python build_extend_utils_cffi.py
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/root/Project/Image-based_Cabinet_Modeling/pvnet/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
gcc -pthread -B /root/anaconda2/envs/image_cabinet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda2/envs/image_cabinet/include/python3.6m -c _extend_utils.c -o ./_extend_utils.o
gcc -pthread -shared -B /root/anaconda2/envs/image_cabinet/compiler_compat -L/root/anaconda2/envs/image_cabinet/lib -Wl,-rpath=/root/anaconda2/envs/image_cabinet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-9.0/lib64/libcudart.so -lstdc++ -o ./_extend_utils.cpython-36m-x86_64-linux-gnu.so
/root/anaconda2/envs/image_cabinet/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script
/root/anaconda2/envs/image_cabinet/compiler_compat/ld:./lib/libceres.so:0: syntax error
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 41, in <module>
    ffibuilder.compile(verbose=True)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/root/anaconda2/envs/image_cabinet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

How should I do?

**Comment by pengsida** [comment]
Please ensure the OS is 64 bit.

**Comment by Hao-HUST** [comment]
Of course, we use 64-bit 16.04 ubuntu OS.

**Comment by pengsida** [comment]
Remove `*.o` in `src` and compile again.

**Comment by pengsida** [comment]
It seems that `libceres.so` is not linked to `libceres.so.2.0.0`, as referred in this issue https://github.com/binance-exchange/binacpp/issues/15

**Comment by Hao-HUST** [comment]
Should I need to modify the CmakeLists.txt file in extend_utils/src/ according to my own env?

**Comment by pengsida** [comment]
No

**Comment by pengsida** [comment]
> Should I need to modify the CmakeLists.txt file in extend_utils/src/ according to my own env?

Please check if the soft link is broken

**Comment by Hao-HUST** [comment]
What is your Python version? Mine is Python 3.6.7, is that fine?

**Comment by pengsida** [comment]
Yes

**Comment by Hao-HUST** [comment]
I modified the build_extend_utils_cffi.py script, and change the ceres_library path from './lib/libceres.so' to './lib/libceres.so.2.0.0', the script of 'build_extend_utils_cffi.py' compiled successful.

**Comment by Hao-HUST** [comment]
> It seems that `libceres.so` is not linked to `libceres.so.2.0.0`, as referred in this issue [binance-exchange/binacpp#15](https://github.com/binance-exchange/binacpp/issues/15)

As you mentioned, the soft link is broken. My solution is to remove the libceres.so and libceres.so.2, and rebuild the soft link again:

rm libceres.so
rm libceres.so.2
ln -s libceres.so.2.0.0 libceres.so.2
ln -s libceres.so.2 libceres.so
