### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ‘LINEMOD/renders/cat/0_RT.pkl'

### ISSUE THREAD

**Issue by Hao-HUST** [zju3dv/pvnet#19]
Hi, 

Could you please share your Synthesize images for training? It seems that not easy to use the Pvnet-rendering scripts to synthesize images by ourselves.

Best

**Comment by pengsida** [comment]
We get fun from programming by doing hard things.
The synthetic data is so big that I have no enough cloud storage to upload. Sorry.

**Comment by pengsida** [comment]
I upload rendering images of cat: https://1drv.ms/u/s!AtZjYZ01QjphgREic0VEccASuBae
Download it, unzip it and move it to `LINEMOD/renders/cat`

**Comment by Hao-HUST** [comment]
Thanks, I used the pvnet-rendering scripts to render images. 

It is true that the size of the rendering images is too large.

**Comment by AingLee** [comment]
> I upload rendering images of cat: https://1drv.ms/u/s!AtZjYZ01QjphgREic0VEccASuBae
> Download it, unzip it and move it to `LINEMOD/renders/cat`

I have already moved the synthesized images downloaded from above link to the folder of `LINEMOD/renders/cat`, but when I started to train, I still got an error as following. It seems that the fuse folder is missing. What should I do then?

-cfg_file configs/linemod_train.json --linemod_cls cat
/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
motion state False
Traceback (most recent call last):
  File "tools/train_linemod.py", line 358, in <module>
    train_net()
  File "tools/train_linemod.py", line 312, in train_net
    has_render_set=True)
  File "/home/lee/Desktop/research_code/pvnet/lib/utils/data_utils.py", line 228, in __init__
    self.fuse_set=self.collect_fuse_info()
  File "/home/lee/Desktop/research_code/pvnet/lib/utils/data_utils.py", line 314, in collect_fuse_info
    mask=imread(os.path.join(self.linemod_dir,data['dpt_pth']))
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/lee/Desktop/research_code/pvnet/data/LINEMOD/fuse/0_mask.png'
