### ISSUE TITLE
LinkError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by flowtcw** [zju3dv/pvnet#40]
(zhangjun) yanglu@yanglu:~/zhangjun/pvnet/lib/utils/extend_utils$ python build_extend_utils_cffi.py
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/home/yanglu/zhangjun/pvnet/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
gcc -pthread -B /home/yanglu/anaconda3/envs/zhangjun/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yanglu/anaconda3/envs/zhangjun/include/python3.6m -c _extend_utils.c -o ./_extend_utils.o
gcc -pthread -shared -B /home/yanglu/anaconda3/envs/zhangjun/compiler_compat -L/home/yanglu/anaconda3/envs/zhangjun/lib -Wl,-rpath=/home/yanglu/anaconda3/envs/zhangjun/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-8.0/lib64/libcudart.so -lstdc++ -o ./_extend_utils.cpython-36m-x86_64-linux-gnu.so
gcc: error: /usr/local/cuda-8.0/lib64/libcudart.so: No such file or directory
Traceback (most recent call last):
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 39, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/yanglu/anaconda3/envs/zhangjun/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by flowtcw** [comment]
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by flowtcw** [comment]
(base) yanglu@yanglu:~/zhangjun/pvnet/lib/utils/extend_utils$ cd /usr/local
(base) yanglu@yanglu:/usr/local$ ls
bin  cuda  cuda-10.0  etc  games  include  lib  man  sbin  share  src
(base) yanglu@yanglu:/usr/local$

**Comment by flowtcw** [comment]
i find it :Revise the cuda_include and dart in build_extend_utils_cffi.py to be compatible with the CUDA in your computer.

**Comment by robotSunGina** [comment]
> i find it :Revise the cuda_include and dart in build_extend_utils_cffi.py to be compatible with the CUDA in your computer.

Hello, after revising the cuda_include and dart in build_entend_utils_cffi.py, do you have other problems ,like

python build_extend_utils_cffi.py
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/home/robot/Documents/PVNet/pvnet-master/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
gcc -pthread -B /home/robot/anaconda3/envs/PVNET/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/robot/anaconda3/envs/PVNET/include/python3.6m -c _extend_utils.c -o ./_extend_utils.o
gcc -pthread -shared -B /home/robot/anaconda3/envs/PVNET/compiler_compat -L/home/robot/anaconda3/envs/PVNET/lib -Wl,-rpath=/home/robot/anaconda3/envs/PVNET/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-9.0/lib64/libcudart.so -lstdc++ -o ./_extend_utils.cpython-36m-x86_64-linux-gnu.so
/home/robot/anaconda3/envs/PVNET/compiler_compat/ld:./lib/libceres.so: file format not recognized; treating as linker script
/home/robot/anaconda3/envs/PVNET/compiler_compat/ld:./lib/libceres.so:0: syntax error
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 39, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/robot/anaconda3/envs/PVNET/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet/issues/14

**Comment by robotSunGina** [comment]
> #14

thank you, this problem is solved, but when i compile demo.py, there is another problem,like 
ImportError: libceres.so.2: cannot open shared object file: No such file or directory,
and 
![image](https://user-images.githubusercontent.com/45038911/60639428-ace65980-9df0-11e9-99da-3e97016ceabb.png)
sorry for wasting your time, i tried to solve it, but i failed

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/60642137-5b29e780-9e61-11e9-94ba-f1b81b2b40f4.png)

**Comment by robotSunGina** [comment]
> ![image](https://user-images.githubusercontent.com/11582122/60642137-5b29e780-9e61-11e9-94ba-f1b81b2b40f4.png)
谢谢你的回答啊！
我可以讲中文吗？我不是很清楚这一步具体该怎么操作，直接在终端输入 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib 这句话吗？还是其他方法？

**Comment by pengsida** [comment]
当然可以啦。你用的是pycharm，你就在pycharm里面设置环境变量就好了。在终端里输入那句话没用，而且你要改成你的pvnet路径。

**Comment by robotSunGina** [comment]
> 当然可以啦。你用的是pycharm，你就在pycharm里面设置环境变量就好了。在终端里输入那句话没用，而且你要改成你的pvnet路径。
![image](https://user-images.githubusercontent.com/45038911/60649757-a071f900-9e10-11e9-9ce5-39753d30d59f.png)


你好，请问是这样设置环境变量的吗？可是，from lib.utils.extend_utils._extend_utils import lib, ffi这句话中lib和ffi底下仍然还有红线

**Comment by pengsida** [comment]
对的，有红线正常吧，能跑吗

**Comment by robotSunGina** [comment]
> 对的，有红线正常吧，能跑吗

![image](https://user-images.githubusercontent.com/45038911/60650335-f98e5c80-9e11-11e9-9d97-48589a24139d.png)
我在demo.py和extend_utils.py下面都加了LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/robot/Documents/PVNet/pvnet-master/lib/utils/extend_utils/lib这句话，还显示图片上的错误，不知道我是不是有地方还没配置好

**Comment by pengsida** [comment]
如果你是在终端运行`python tools/demo.py`, 只要在终端里输入`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib`，就可以跑了。
如果是在pycharm里运行，是在这里设置
![image](https://user-images.githubusercontent.com/11582122/60652473-e1065c80-9e7a-11e9-957b-13fa98606f3c.png)

**Comment by robotSunGina** [comment]
> 如果你是在终端运行`python tools/demo.py`, 只要在终端里输入`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/pvnet/lib/utils/extend_utils/lib`，就可以跑了。
> 如果是在pycharm里运行，是在这里设置
> ![image](https://user-images.githubusercontent.com/11582122/60652473-e1065c80-9e7a-11e9-957b-13fa98606f3c.png)

![image](https://user-images.githubusercontent.com/45038911/60673612-252b3a00-9e46-11e9-93e2-2a39e06af89e.png)
设置了环境变量后，问题还存在，没法运行起来，貌似是libceres.so.2这个问题，不知道你之前是否遇到相同问题

**Comment by pengsida** [comment]
我没用pycharm跑过这个代码。你可以试试在终端跑这代码。
这个问题就是你LD_LIBRARY_PATH的环境变量没设置好，所以找不到libceres.so.2。
