### ISSUE TITLE
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by MyungHaSong** [zju3dv/pvnet#95]
Hi,
first of all thank you for sharing your code.

I follwed your guide and got the following error:

python build_extend_utils_cffi.py
generating ./_extend_utils.c
(already up-to-date)
the current directory is '/workspace/pvnet/lib/utils/extend_utils'
running build_ext
building '_extend_utils' extension
gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.6m -c _extend_utils.c -o ./_extend_utils.o
gcc -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_extend_utils.o src/mesh_rasterization.cpp.o src/farthest_point_sampling.cpp.o src/uncertainty_pnp.cpp.o src/nearest_neighborhood.cu.o ./lib/libceres.so ./lib/libglog.so /usr/local/cuda-8.0/lib64/libcudart.so -lstdc++ -o ./_extend_utils.cpython-36m-x86_64-linux-gnu.so
gcc: error: /usr/local/cuda-8.0/lib64/libcudart.so: No such file or directory
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/opt/conda/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/opt/conda/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/opt/conda/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/opt/conda/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/opt/conda/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 39, in <module>
    ffibuilder.compile(verbose=True)
  File "/opt/conda/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/opt/conda/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/opt/conda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/opt/conda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

what should I do?

**Comment by AingLee** [comment]
Revise the cuda_include and cudart in build_extend_utils_cffi.py to be compatible with the CUDA in your computer.
