### ISSUE TITLE
Training Network

### ISSUE THREAD

**Issue by AingLee** [zju3dv/pvnet#98]
@pengsida , thank you for sharing the source code. Right now, I run into the an issue related to CUDA out of memory while I am trying to re-train the network. I tried to reduce the batch size from 32 to 8, so that I can process the training. I was wondering how you can train the network with 32 batch size. Another thing is that can the training with reducing batch size effect the performance or not be as good as the one with the original/larger batch size? Last but not least, do you have any strategies to show/verify that the network being trained is on the right way?

Traceback (most recent call last):
  File "/home/lee/Desktop/research_code/pvnet/tools/train_linemod.py", line 372, in <module>
    train_net()
  File "/home/lee/Desktop/research_code/pvnet/tools/train_linemod.py", line 355, in train_net
    train(net, optimizer, train_loader, epoch)
  File "/home/lee/Desktop/research_code/pvnet/tools/train_linemod.py", line 149, in train
    seg_pred, vertex_pred, loss_seg, loss_vertex, precision, recall = net(image, mask, vertex, vertex_weights)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lee/Desktop/research_code/pvnet/tools/train_linemod.py", line 86, in forward
    seg_pred, vertex_pred = self.net(image)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lee/Desktop/research_code/pvnet/lib/networks/model_repository.py", line 74, in forward
    fm=self.up2storaw(fm)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/modules/upsampling.py", line 131, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
  File "/home/lee/Desktop/research_code/pvnet/env/lib/python3.6/site-packages/torch/nn/functional.py", line 2563, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 744.00 MiB (GPU 0; 10.72 GiB total capacity; 7.54 GiB already allocated; 256.69 MiB free; 1.48 GiB cached)

**Comment by pengsida** [comment]
1. I train the network with 4 gpus.
2. Maybe. I am not sure.
3. Overfit an image. If it succeeds, then the training is probably correct.

**Comment by AingLee** [comment]
Did you train the network with 4 gpus on a single machine (combine 4 gpus on one motherboard) or on separate machines by creating a server (I am not sure about this)? If with the different ones, would you mind sharing me the way how to do it or any tutorials.
I have re-trained the pvnet on Cat object, and I found that only at epoch 2 the recall (maybe also precision) started to decrease from 0.98xxx to 0.91xxx after reaching the peak at epoch 1, so that I stopped the training. I would like to know that your best result was obtained at some epochs or at the end which was epoch 199. When the overfiting happens, what do you usually do (tune parameters? what kinds?)?

**Comment by pengsida** [comment]
1. I train the network on a single machine.
2. Our network converges around 190 ~ 200 epochs. The best result usually does not locate at 199 epoch. If you want to avoid overfitting, you need to split a val from the training set and choose the best result on the val set.

**Comment by AingLee** [comment]
Thank you so much and I really appreciate it. I hope that there would be more chances that I could learn something more from you.

**Comment by pengsida** [comment]
Any dicussion is welcomed!
You could contact with me through email.
